foreground              #FFFFFF
background              #1E202D
selection_foreground    #1E202D
selection_background    #FFFFFF
cursor                  #BDCED1
cursor_text_color       #090909

active_tab_foreground     #1E202D
active_tab_background     #595D71
inactive_tab_foreground   #595D71
inactive_tab_background   #1E202D

# black
color0      #292E52
color8      #575F8F

# red
color1      #CCF7FF
color9      #AAE5F0

# green
color2      #CCD1FF
color10     #AAB2F0

# yellow
color3      #CCD5FF
color11     #AAB6F0

# blue
color4      #9AA4E6
color12     #9AA4E6

# magenta
color5      #9AA2E6
color13     #9AA2E6

# cyan
color6      #9AA6E6
color14     #9AA6E6

# white
color7      #CCF7FF
color15     #AAE5F0
