[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT0
adapter = ADP1
poll-interval = 5


; === Débranché (décharge) : icône selon le niveau ===
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%

; Icônes (Font Awesome / Nerd Fonts) : vide → plein
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; === En charge : petite animation ===
format-charging = <animation-charging>  <label-charging>
label-charging = %percentage%%

; On réutilise la même “rampe” comme animation
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 500

; === Pleine ===
format-full = "  <label-full>"
label-full = %percentage%%

; === Très faible ===
format-low = <ramp-capacity>  <label-low>
label-low = %percentage%%
