[module/powermenu]
type = custom/menu
expand-right = true
format-spacing = 1

; Boutons d’ouverture/fermeture du menu
label-open = ""
label-open-foreground = ${colors.primary}
label-close = ""
label-close-foreground = ${colors.alert}
label-separator = "  "

menu-0-0 = " Verrouiller"
menu-0-0-foreground = ${colors.primary}
menu-0-0-exec = i3lock -c 000000

menu-0-1 = "⏾ Veille"
menu-0-1-foreground = ${colors.primary}
menu-0-1-exec = systemctl suspend

menu-0-2 = " Redémarrer"
menu-0-2-foreground = ${colors.primary}
menu-0-2-exec = systemctl reboot

menu-0-3 = " Déconnexion"
menu-0-3-foreground = ${colors.alert}
menu-0-3-exec = i3-msg exit

menu-0-4 = " Éteindre"
menu-0-4-foreground = ${colors.alert}
menu-0-4-exec = systemctl poweroff
